remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
title: Capstone Project
description: Nora Hallqvist, Anna Midgley, Xinyu Kang, Hongyi Sun, Bowen 

author:
  name: Nora Hallqvist, Anna Midley, Xinyu Kang, Hongyi Sun, Bowen 
  url: https://norahellstadius.github.io/ 


